RelativeLayout:
    canvas:
        Rectangle:
            pos: 0,0
            size: 100,100

        Ellipse:
            segments: 180
            angle_start: 0
            angle_end: 270
            pos: 200,200
            size: 100,100

        Ellipse:
            segments: 3
            angle_start: 0
            angle_end: 360
            pos: 350, 350
            size: 100, 100